# fly.toml app configuration file generated for little-tickets on 2024-09-03T11:46:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'little-tickets'
primary_region = 'eze'

[build]

[env]
  BASE_URL = "https://little-tickets.fly.dev"  
  DATABASE_TABLES_PREFIX="lt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
